# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

NITROFSDIR  := nitrofiles

# User config

NAME		:= dscon
GAME_TITLE	:= dscon
GAME_SUBTITLE	:= Use your DS as a wireless controller

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
