# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# Libraries
# ---------

LIBS		:= -ldswifi9 -lnds9 -lnflib
LIBDIRS		:= $(BLOCKSDS)/libs/dswifi \
			   $(BLOCKSDS)/libs/libnds \
			   $(BLOCKSDS)/libs/nflib

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9
